Feat: Criando interface gráfica
guivahl/programacao-de-sistemas pull request #27
Opened 2022-10-10 11:52 UTC by Fernanda-Kipper

closes #22 
closes #21 
closes #23 
closes #24 

## O que foi feito:

Foi criada a interface gráfica, juntamente com a atualização dos componentes existentes para que os mesmos se conversassem.

### GUI
A classe GUI abriga todos os componentes da interface gráfica, como o painel dos valores da stack, painel de registradores, terminal e botão.

### Logger
A classe Logger implementa a função de logger da aplicação, onde todos componentes da máquina podem lançar mensagens de sucesso e erro durante a execução e os mesmos serão mostrados no terminal da interface gráfica.

## Screenshots
<img width="800" alt="Captura de Tela 2022-10-10 às 08 51 11" src="https://user-images.githubusercontent.com/61896274/194860029-8fb15a2c-dde5-4469-b417-6b7f1b51bb3f.png">
o exibidos no terminal da interface

2022-10-10 12:16 UTC, guivahl commented on src/vm/Components/Logger/Logger.java
> +	}
acho q aqui da pra a identação não pegou

2022-10-10 12:17 UTC, guivahl commented on src/vm/Components/Logger/Logger.java
> +        notifyObservers();
esses dois metodos

setChanged();
notifyObservers();
        
são da classe Observable?

2022-10-10 12:21 UTC, guivahl commented on src/vm/Components/Register.java
> +    public String identifier;
pq mudamos esse atributo para public?

2022-10-10 12:24 UTC, guivahl commented on src/vm/Components/Register.java
> +            String expectationMessage = String.format("Size of register %s is invalid!", identifier);
essa variavel n deveria seguir expection? de "mensagem de exceção"

2022-10-12 20:09 UTC, Fernanda-Kipper commented on src/vm/Components/Logger/Logger.java
> +	}
vdd, vou ajustar!

2022-10-12 20:09 UTC, Fernanda-Kipper commented on src/vm/Components/Logger/Logger.java
> +        notifyObservers();
Simm, são métodos da super classe

2022-10-12 20:10 UTC, Fernanda-Kipper commented on src/vm/Components/Register.java
> +    public String identifier;
eu mudei pra public pq queria acessar pela interface pra saber o nome de cada registrador, acha que não faz sentido?

2022-10-12 20:10 UTC, Fernanda-Kipper commented on src/vm/Components/Register.java
> +            String expectationMessage = String.format("Size of register %s is invalid!", identifier);
Hmmm verdade hehe, vou ajustar

2022-10-13 14:05 UTC, guivahl commented
LGTM!

2022-10-26 23:54 UTC, vinicius-munchow requested changes

2022-10-26 23:54 UTC, vinicius-munchow commented on src/vm/App.java
> +public class App implements ActionListener {
ping meramente ilustrativo mas vai ser necessario resolver o conflito que o merge do Assembler gerou entre as branchs main e a desse PR

2022-11-07 02:51 UTC, Fernanda-Kipper commented on src/vm/Components/SourceCodeHandler.java
> +    private static final int WORD_SIZE = 16;
Nãoo, vou remover

2022-11-07 02:52 UTC, Fernanda-Kipper commented on src/vm/App.java
> +public class App implements ActionListener {
Boa! Fiz um rebase para resolver e já aproveitei para integrar a execução do assembler com o a interface

2022-11-07 02:52 UTC, merged